name: CI Workflow

# Trigger the workflow on push or pull request to dev and master
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VENV_DIR: ${{ github.workspace }}/myenv

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub token for private repos

    - name: Set Up Python Environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conda
        conda env create -f environment.yaml
        source activate myenv

    - name: Run Code Quality Checks
      run: |
        source activate myenv
        isort .
        black .
        flake8 .

    - name: Run Unit Tests
      run: |
        source activate myenv
        pytest
