name: CI Workflow

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        auto-activate-base: false
        environment-file: environment.yaml  # Ensure you have an environment.yml file in your repo
        activate-environment: myenv        # Name of the environment from environment.yml
        use-mamba: true                    # Optional: use Mamba (a faster package manager for Conda)

    - name: Install Dependencies
      run: |
        conda activate myenv
        conda info --envs               # Check the environment
        conda list                      # List installed packages

    - name: Run Code Quality Checks
      run: |
        conda activate myenv
        isort .
        black .
        flake8 .

    - name: Run Unit Tests
      run: |
        conda activate myenv
        pytest