name: CI Workflow

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        auto-activate-base: false
        environment-file: environment.yaml  # Make sure this file exists
        activate-environment: myenv        # Name of the Conda environment

    - name: Source Conda and Activate Environment
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh  # Source conda.sh to configure shell
        conda activate myenv

    - name: Install Dependencies
      run: |
        conda activate myenv
        conda info --envs               # Check the environment
        conda list                      # List installed packages

    - name: Run Code Quality Checks
      run: |
        conda activate myenv
        isort .
        black .
        flake8 .

    - name: Run Unit Tests
      run: |
        conda activate myenv
        pytest
